import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Authentication from "../components/auth/Authentication";
import { supabase } from "../utils/supabaseClient";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [session, setSession] = useState(null);

  useEffect(() => {
    setSession(supabase.auth.session());

    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session);
    });
  }, []);

  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      {!session && <Authentication />}
      {session && (
        <>
          <h1>Welcome to Trim!</h1>
        </>
      )}
    </div>
  );
}
